#!/usr/bin/env python3
"""Write requirements/host.lock from requirements/host.in.

    python3 scripts/update_host_lock.py          # rewrite the lock
    python3 scripts/update_host_lock.py --check  # exit 1 if it would change

RELEASE-6. The host venv is installed with
`pip install --require-hashes --no-deps --only-binary=:all: -r requirements/host.lock`,
so the lock is the complete list of what may land there, each pinned to an
exact version and to the sha256 of every wheel file a supported host can pick:
CPython 3.11-3.14 on x86_64 glibc (manylinux), or a pure-Python wheel. No
sdist is listed, so pip has nothing it could build and nothing to fetch a
build backend for. Hashes come from PyPI's JSON API over TLS - the same source
pip-compile --generate-hashes uses - and this script installs nothing.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "requirements/host.in"
LOCK = ROOT / "requirements/host.lock"
PYTHONS = ("cp311", "cp312", "cp313", "cp314")
_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([A-Za-z0-9_.+!-]+)\s*(;.*)?$")

HEADER = """\
# GENERATED by scripts/update_host_lock.py from requirements/host.in - do not edit.
#
# The complete, hash-locked contents of the omodachi host venv. The installer
# (scripts/install_host.py) installs exactly this with
#   pip install --isolated --require-hashes --no-deps --only-binary=:all: -r requirements/host.lock
# into a freshly created venv, then omodachi-core itself with
#   --no-index --no-deps --no-build-isolation
# so its build backend is the setuptools pinned here. Wheels only (CPython
# 3.11-3.14, x86_64 manylinux, or pure Python); no sdist is listed.
"""


def usable(filename: str) -> bool:
    if not filename.endswith(".whl"):
        return False
    python, abi, platform = filename[:-4].split("-")[-3:]
    if platform == "any":
        return abi == "none" and all(tag.startswith("py3") or tag == "py2"
                                     for tag in python.split("."))
    return (python in PYTHONS and abi == python
            and all(tag.startswith("manylinux") and tag.endswith("_x86_64")
                    for tag in platform.split(".")))


def files(name: str, version: str) -> list[tuple[str, str]]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as response:
        release = json.load(response)
    chosen = sorted((entry["filename"], entry["digests"]["sha256"])
                    for entry in release["urls"]
                    if not entry.get("yanked") and usable(entry["filename"]))
    if not chosen:
        raise SystemExit(f"{name}=={version} has no wheel a host can use")
    return chosen


def render() -> str:
    out = [HEADER]
    for line in SOURCE.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        match = _PIN.match(line)
        if not match:
            raise SystemExit(f"host.in: not an exact pin: {line!r}")
        name, version, marker = match[1], match[2], (match[3] or "").strip()
        chosen = files(name, version)
        out.append(f"{name}=={version}" + (f" {marker}" if marker else "") + " \\")
        for index, (filename, digest) in enumerate(chosen):
            last = index == len(chosen) - 1
            out.append(f"    --hash=sha256:{digest}" + ("" if last else " \\"))
        out.append("    # " + ", ".join(sorted({f.split('-')[-3] + '-' + f[:-4].split('-')[-1].split('.')[0]
                                               for f, _ in chosen})))
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = LOCK.read_text() if LOCK.is_file() else ""
        if current != text:
            print(f"{LOCK} is out of date", file=sys.stderr)
            return 1
        return 0
    LOCK.write_text(text)
    print(f"wrote {LOCK}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
